In [2]:
Задание 1
В недалеком будущем, появляются машины, которые умеют летать, но мало что изменилось, 
и многие водители продолжают нарушать скоростной режим даже в воздухе. 
Один находчивый предприниматель смог создать камеру-радар, которая следит за скоростным режимом в воздухе. 
Она расположена на специальном дроне, 
который левитирует на одной точке. 
Из-за небольшого раскачивания, радар может выдавать неточные данные 
(следует рассматривать погрешность в +-5 км/ч). 
Если водитель летел со скоростью, меньше минимальной(120 км/ч), 
то его штрафуют на 10 долларов и лишают летательных прав на месяц. 
Если же он превысил (разрешенная скорость 235 км) на 20-34 км/ч, то его штрафуют на 10 долларов без лишения прав, 
на 35-49 —- штраф на 25 долларов без лишения, 
а если водитель превысил на 50+ —- штраф 100 долларов и лишение прав. 
Предприниматель договорился с государством, и его оборудование установили по всей стране. 
С каждого штрафа мужчина будет получать 10%. 
Задача: по данному массиву вычислить прибыль предпринимателя и количество людей, лишенных летательных прав. 

Массив: n_322 = [189, 147, 211, 278, 200, 270, 164, 243, 227, 238, 122, 201, 177, 178, 207, 169, 219, 278, 123, 230, 221, 141, 197, 138, 262, 208, 147, 235, 130, 161, 208, 236, 262, 225, 236, 151, 278, 179, 235, 209, 183, 208, 192, 218, 182, 243, 119, 209, 174, 139, 162, 225, 136, 161, 139, 166, 207, 258, 167, 219, 157, 213, 262, 268, 247, 207, 255, 190, 217, 181, 143, 125, 280, 150, 147, 205, 266, 263, 222, 153, 257, 147, 180, 174, 276, 269, 114, 270, 179, 132, 172, 123, 208, 250, 163, 217, 118, 182, 213, 188, 291, 320]

Массив может быть другим.
Не используйте циклы.


SyntaxError: invalid syntax (<ipython-input-2-73fad3a2fc57>, line 1)

In [20]:
import numpy as np
n_322 = [189, 147, 211, 278, 200, 270, 164, 243, 227, 238, 122, 201, 177, 178, 207, 169, 219, 278, 123, 230, 221, 141, 197, 138, 262, 208, 147, 235, 130, 161, 208, 236, 262, 225, 236, 151, 278, 179, 235, 209, 183, 208, 192, 218, 182, 243, 119, 209, 174, 139, 162, 225, 136, 161, 139, 166, 207, 258, 167, 219, 157, 213, 262, 268, 247, 207, 255, 190, 217, 181, 143, 125, 280, 150, 147, 205, 266, 263, 222, 153, 257, 147, 180, 174, 276, 269, 114, 270, 179, 132, 172, 123, 208, 250, 163, 217, 118, 182, 213, 188, 291, 320]
dron = 5
massiv = np.array(n_322)
print(massiv)
print("\n")

men_120 = (massiv < 125)
kolvo_120 = len(massiv[men_120])
print(kolvo_120)
print(massiv[men_120])
print("\n")

plus_20 = (massiv >= 260) & ( massiv <= 274)
kolvo_20 = len(massiv[plus_20])
print(kolvo_20)
print(massiv[plus_20])
print("\n")

plus_35 = (massiv >= 275) & ( massiv <= 289)
kolvo_35 = len(massiv[plus_35])
print(kolvo_35)
print(massiv[plus_35])
print("\n")

plus_50 = (massiv >= 290) 
kolvo_50 = len(massiv[plus_50])
print(kolvo_50)
print(massiv[plus_50])
print("\n")

pf = kolvo_120 + kolvo_20 + ((kolvo_35 *25)*10/100) + ((kolvo_35 *100)*10 /100 )
print(pf)

kolvo = kolvo_120 + kolvo_20 + kolvo_35 + kolvo_50
print(kolvo)

[189 147 211 278 200 270 164 243 227 238 122 201 177 178 207 169 219 278
 123 230 221 141 197 138 262 208 147 235 130 161 208 236 262 225 236 151
 278 179 235 209 183 208 192 218 182 243 119 209 174 139 162 225 136 161
 139 166 207 258 167 219 157 213 262 268 247 207 255 190 217 181 143 125
 280 150 147 205 266 263 222 153 257 147 180 174 276 269 114 270 179 132
 172 123 208 250 163 217 118 182 213 188 291 320]


6
[122 123 119 114 123 118]


9
[270 262 262 262 268 266 263 269 270]


5
[278 278 278 280 276]


2
[291 320]


77.5
22


In [ ]:
Задание 2
Работа с файлом tips.csv
Найти кто больше суммарно оставил чаевых(tip) мужчины или женщины (sex) 

In [136]:
import pandas as pd
import numpy as np
col = ['NaN' 'total_bill'   'tip'     'sex' 'smoker'   'day'    'time' 'size']
tips = pd.read_csv('C:/Users/Михаил/Desktop/kr/tips.csv')
e =pd.DataFrame(tips)
e.columns=['index','total_bill','tip','sex','smoker','day','time','size']
otvet = e.groupby('sex')["tip"].sum()
print(otvet)


sex
Female    246.51
Male      485.07
Name: tip, dtype: float64


In [137]:
По полученным данным видим, что мужчина оставили намного больше чаевых чем женщины

SyntaxError: invalid syntax (<ipython-input-137-4c54ff93a5c1>, line 1)