# Библиотека Numpy

Для того, чтобы работать с объектами и фукциями библиотеки 'numpy', её следует подключить. Обычно для этого в начале программы пишут:
```python
import numpy as np
```
Теперь обратиться к любой из функций библиотеки можно через сокращение **np**.

<p style="width: 715px;" >
<i>Импортируйте библиотеку numpy в поле ниже и нажмите кнопку запуска кода, расположенную выше.<img src="img/play.png" width="24" height="24" align="right"/></i>
</p>

In [ ]:
import numpy as np

Главным объектом при работе с этой библиотекой является многомерный массив `ndarray`, который представляет собой таблицу элементов одного типа. Каждое из измерений называется осью (`axes`), а количество измерений -- рангом (`rank`).

<img src="img/array.gif">

Существует множество способов создания таких массивов. Рассмотим наиболее часто используемые из них.

**Способы создания массивов ndarray:**

1) Путём преобразования стандартных списков Python, используя функцию `array`:
```python
a = np.array([2, 3, 4])
```
Следует обратить внимание, что аргументом данной функции является именно список (`list`), а не последовательность чисел -- не забывайте писать квадратные скобки **[ ]** ! 

В случае, если Вам требуется создать многомерный массив, указывайте последовательно содержимое каждого из измерений:

```python
b = np.array([[1.5, 2, 3], [4, 5, 6]])
```
Такой вариант создания `ndarray` работает не только со списками, но и с любыми другими контейнерами языка Python, например со стандартными кортежами (`tuple`) или с любыми другими типами, которые допускают перечисление элементов.

_Создайте одномерный, двумерный и трехмерный массивы, заполненные числами. Напечатайте результат. Для этого достаточно написать имя объекта в строке кода:_
```python
a = np.array([2, 3, 4])
a
```
_Обратите внимание, что такой способ позволяет вывести только одно значение - будет напечатан результат выполнения последней операции, а данном примере - значение `a`. Если требуется вывести какие-то промежуточные результаты, используйте функцию `print` или разбейте код на несколько ячеек._

In [ ]:
b= np.array([2,4,6])
c= np.array([[1,2,3],[2,3,4]])
d= np.array([[1,2,3],[2,3,4],[4,3,2]])
print(b)
print("\n")
print(c)
print("\n")
print(d)

[2 4 6]


[[1 2 3]
 [2 3 4]]


[[1 2 3]
 [2 3 4]
 [4 3 2]]


2) Можно создавать массивы, заполненные начальными значениями, для этого часто используют такие функции, как 'zeros' или 'ones', указывая в скобках размер измерений:
```python
a1 = np.zeros((2, 5))
a2 = np.ones((2, 2, 5))
```
Обратите внимание на двойные скобки: внешние скобки это вызов функции. В данном случае функции вызываются с одним аргументом - кортежем (`tuple`), задающим размер создаваемого массива. Вложенные скобки обрамляют этот кортеж. Если не написать вложенные скобки, то разделённе запятыми числа будут переданы функции как несколько аргументов. Например, вторым (необязательным) аргументом функции `np.zeros` является тип данных массива, и вызов `np.zeros(2, 5)` будет пониматься как попытка создать массив из элементов типа `5`, что является ошибкой.

<i>Поэксперементируйте с созданием массивов с помощью функций `np.zeros` и `np.ones`.</i>

In [ ]:

b1 =np.zeros((2,3,6))
b2 =np.ones((9,4,9))
print(b1)
print(b2)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 

3) Можно создавать массивы, заполненные арифметическими прогрессиями (последовательностями чисел). Для этого можно использовать функцию `arange`:
```python
a = np.arange( 15, 35, 5 )
```

Аргументами функции являются: начальное значение, конечное значение и **шаг**. 

Начальное значение и шаг -- необязательные аргументы, по умолчанию `начальное значение = 0`, а `шаг = 1`.


В случае, если требуется создать многомерный массив, можно "разбить" полученный с помощью `arange` одномерный, используя функцию `reshape`:
```python
a = np.arange(15).reshape(3, 5)
```

Обратите внимание, что конечный элемент **не** будет включён в содержимое массива. 

_Проверьте это утверждение._

_Поработайте с функцией `reshape`: создайте двумерные, трёхмерные и n-мерные массивы. Следите за тем, чтобы количество элементов исходного одномерного массива делилось на число размерностей создаваемого многомерного!_

In [ ]:
b = np.arange(0,100,2)
print(b)
c = np.arange(0,120,2).reshape(15,4)
print(c)




[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


array([[  0,   2,   4,   6],
       [  8,  10,  12,  14],
       [ 16,  18,  20,  22],
       [ 24,  26,  28,  30],
       [ 32,  34,  36,  38],
       [ 40,  42,  44,  46],
       [ 48,  50,  52,  54],
       [ 56,  58,  60,  62],
       [ 64,  66,  68,  70],
       [ 72,  74,  76,  78],
       [ 80,  82,  84,  86],
       [ 88,  90,  92,  94],
       [ 96,  98, 100, 102],
       [104, 106, 108, 110],
       [112, 114, 116, 118]])

В качестве альтернативы `arange` можно использовать функцию `linspace`.

Аргументами которой являются: начальное значение, конечное и **количество элементов**. 

Данную функцию чаще всего используют в случае, если требуется создать массивы чисел с плавающей точкой, равномерно распределёных между граничных значений.

_Проверьте, включается ли последний элемент в данном случае? Ответ запишите во втором поле._

In [ ]:
b1 = np.linspace(0.5,110.5,40)
print(b1)


[  0.5          3.32051282   6.14102564   8.96153846  11.78205128
  14.6025641   17.42307692  20.24358974  23.06410256  25.88461538
  28.70512821  31.52564103  34.34615385  37.16666667  39.98717949
  42.80769231  45.62820513  48.44871795  51.26923077  54.08974359
  56.91025641  59.73076923  62.55128205  65.37179487  68.19230769
  71.01282051  73.83333333  76.65384615  79.47435897  82.29487179
  85.11538462  87.93589744  90.75641026  93.57692308  96.3974359
  99.21794872 102.03846154 104.85897436 107.67948718 110.5       ]
Последний элемент включается


**Последний элемент включается**

**Наиболее важными атрибутами (свойствами) массивов `ndarray` явлются:**
1. `ndarray.ndim` -- количество осей (измерений) массива. 
2. `ndarray.shape` -- форма массива. Возвращает количество элементов массива в каждом из измерений. Для матрицы `a` из n строк и m столбцов, код `a.shape` вернёт `(n, m)`.
3. `ndarray.size` -- суммарное количество элементов массива (равно произведению элементов a.shape).
4. `ndarray.dtype` -- вернёт тип элементов в массиве.

_Проверьте работу каждого из этих свойств на произвольном массиве `ndarray`._

In [ ]:
b1 = np.array([[1,2,3,91],[2,6,5,4],[1,45,21,54]])

b_ndim = b1.ndim
print(b_ndim)

b_shape = b1.shape
print(b_shape)

b_size = b1.size
print(b_size)

b_dtype = b1.dtype
print(b_dtype)


2
(3, 4)
12
int64


**Арфметические операции**

Основной особенностью `ndarray` является то, как они работают с арифметическими операциями. Если взять два `ndarray` одинакового размера и применить к ним какую-нибудь арифметическую операцию, то получим новый массив, элементы которого получаются применением этой операции к соответствующим парам элементов.

Пример:
```python
a = np.array([20,30,40,50])
b = np.array([0, 1, 2, 3])
a - b
```
вывод:
```python
array([20, 29, 38, 47]).
```
_Проведите арифметические операции (не забудьте про +=, *=..) с произвольными массивами одинаковой формы._

In [ ]:
b1 = np.array([[1,2,3,91],[2,6,5,4],[1,45,21,54]])
b2 = np.array([[0,1,3,4],[1,1,3,2],[0,40,10,45]])

b1 += b1
print(b1)
print("\n")

b1 -= b2
print(b1)
print("\n")

b1 *= b2
print(b1)
print("\n")

print(b1 - b2)
print("\n")
print(b1 + b2)
print("\n")
print(b1 * b2)


[[  2   4   6 182]
 [  4  12  10   8]
 [  2  90  42 108]]


[[  2   3   3 178]
 [  3  11   7   6]
 [  2  50  32  63]]


[[   0    3    9  712]
 [   3   11   21   12]
 [   0 2000  320 2835]]


[[   0    2    6  708]
 [   2   10   18   10]
 [   0 1960  310 2790]]


[[   0    4   12  716]
 [   4   12   24   14]
 [   0 2040  330 2880]]


[[     0      3     27   2848]
 [     3     11     63     24]
 [     0  80000   3200 127575]]


Такая реализация математических операций позволяет записывать большинство вычислений над массивами без использования циклов, которые требуются в других языках программирования. Стиль написания программы, в котором используются подобные операции над целыми массивами называется **векторизованным кодом**. Векторизованный код гораздо компактнее обычного кода с циклами, и позволяет избежать ошибок с неправильной работой с индексами.

Как Вы могли заметить, операция умножения работает также поэлементно. Во многих случаях это удобно, но не следует путать такое умножение с умножением матриц в линейной алгебре, это две разные операции и есть случаи, в которых нужна именно вторая.

Чтобы перемножить 2 матрицы по правилам линейной алгебры, следует применить к ним функцию `np.dot()`:
```python
c = np.dot(a, b)  
```
Для одномерных массивов функция `np.dot()` вычисляет их скалярное произведение.

_Примените поэлементное и матричное умножение к двум матрицам._

In [ ]:
b1 = np.array([2,3,4,5,1])
b2 = np.array([4,2,4,2,1])
b3 = np.dot(b1,b2)
print(b3)
b4 = b1 * b2
print(b4)

41
[ 8  6 16 10  1]


Арифметические операции можно выполнять не только между массивами одинакового размера, но и между массивами и обычными числами. При этом будет сформирован новый массив, каждый элемент которого будет равен результату выполнения операции между соответствующим элементом исходного массива и числом. Например, чтобы умножить все элементы массива `a` на два достаточно написать
```Python
a *= 2
```
при любом размере массива `a`.

Обратите внимание, что при работе с массивами разных типов, результирующий массив будет иметь наиболее общий тип.

Запустите код ниже.

In [ ]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3)) #создаёт массив 2х3, заполненный случайными числами из равномерного распределения в интервале [0, 1)
a *= 3
b += a
a += b

UFuncTypeError: ignored

Появилась ошибка?

**Возможно проблема в том, что мы не можем привести массив чисел с плавающей точкой к массиву с целыми числами**

Обычно вычисления над элементами массива не ограничиваются только четырьмя арифметическими операциями. В библиотеке Numpy реализованы все стандартные математические функции, которые можно применить сразу ко всем элементам массива, например в результате выполнения кода
```python
a = np.arange(1, 5)
np.sqrt(a)
```
будут вычислены квадратные корни всех элементов массива `a`:
```python
array([ 1.,  1.41421356,  1.73205081,  2.])
```

Такие функции в документации Numpy называют универсальными (анг. universal function, сокращённо ufunc).

_Выберите пару (или больше) функций из https://docs.scipy.org/doc/numpy/reference/routines.linalg.html или https://docs.scipy.org/doc/numpy/reference/routines.math.html и проиллюстрируйте их работу в окне ниже._

In [ ]:
b1 = np.array([2,10,2,6])
b2 = np.array([-2,10,4,6])

b3 = np.inner(b1,b2)
print(b3)

c1 = np.array([[2,2],[4,5]])
c2 = np.array([[4,5],[2,1]])
b4 = np.linalg.inv(c1)
print(b4)

b5 = np.linalg.det(c1)
b5

140
[[ 2.5 -1. ]
 [-2.   1. ]]


2.0

**inner= Умножает первый элемент из первого массива с первым элементом из второго массива и суммирует с произведением вторых элементов двух массивов и так далее до конца массива**

**inv = находит обратную матрицу для заданного массива**

**det = находит детерминант  для заданного массива**

Ещё один вид функций, который определён в Numpy, это функции вычисляющие агрегированные показатели по всем элементам массива. Они реализуют такие операции как вычисление суммы всех элементов (функция `np.sum`), нахождения минимального (`np.min`) и максимального (`np.max`) элементов, и многие другие.

Такие функции обычно можно вызвать двумя способами, первый как методы класса `ndarray`, например:
```python
a.sum()
a.min()
a.max()
```

Второй способ как обычную функцию библиотеки Numpy:
```python
np.sum(a)
np.min(a)
np.max(a)
```

Второй вариант позволяет передать функции не только `ndarray`, но и обычные списки Python или любые другие "подходящие" массивы. В этом случае входной массив будет преобразован в `ndarray` перед выполнением операции.
Некоторые из функций могут быть доступны только в одном из вариантов.

_Найдите среднее арифметическое всех элементов двумерного массива, используя изученные функции (массив создайте самостоятельно)._

In [ ]:
c1 = np.array([[2,2,14],[4,5,15],[2,1,2]])
c2 =np.size(c1)
c3 = np.sum(c1)/c2
c3


5.222222222222222

_Дан массив чисел:_

a = np.array([2, 3, 4, -2, 44, 2, 4, 10, 100, 15])

_Элементы массива расположили на числовой прямой (в порядке возрастания). Требуется найти середину минимального отрезка, включающего все числа._

In [ ]:
a = np.array([2, 3, 4, -2, 44, 2, 4, 10, 100, 15])
n =np.size(a)
print(n)
a_min = np.min(a)
a_max = np.max(a)
segment = a_max - a_min
segment_avg = segment / 2
print(segment_avg)


10
51.0


По умолчанию агрегирующие функции проходят по всему массиву. Можно ограничить их работу одним измерением, для вычисления таких значений как "суммы столбцов", "максимумы по строкам" и т.п. Для этого следует указать значение необязательного параметра `axis` в аргументах функции:
```python
b = np.arange(12).reshape(3,4)
b.sum(axis=0) 
b.min(axis=1)
b.cumsum(axis=1) #возвращает накопительную сумму по каждой строке
```
_Определите, за что отвечает аргумент axis = 0 и axis = 1, на примере многомерного массива (n >= 2), создав его первым или третьим способами._

In [ ]:
c1 = np.array([[2,2],[4,5],[40,21]])

d = c1.sum(axis = 0)
print(d)

d1 = c1.max(axis = 1)
print(d1)

[46 28]
[ 2  5 40]


**Сумму элементов массива по строкам**

_В массиве содержится список двумерных матриц (массив трёхмерный). Напишите программу без циклов, которая найдёт сумму элементов каждой из матриц с использованием функции sum()._ 

In [ ]:
a = np.arange(48).reshape(4, 3, 4)
print(a)
print("\n")
b1 =a.sum(axis = 1)
b2 =b1.sum(axis = 1)

print(b2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


[ 66 210 354 498]


**Индексация и срезы по массивам**

Для доступа к элементам массивов `ndarray` используются квадратные скобки. К примеру, `a[2]` -- второй элемент массива `a`.
Таким образом, доступ к элементам одномерных массивов такой же, как и к классическим спискам (`list`) Python.

Также удобно использовать срезы (в квадратных скобках можно указать `начало : конец : шаг`):
```python
a = np.arange(10)**2
print(a[2])
print(a[2:5])
a[:6:2] = -5  #эквивалентно a[0:6:2] = -5 -- с начала до 6 позиции с шагом 2 (каждому второму элементу) устанавливается значение -5
```
Чтобы обратиться к последнему элементу, используйте индекс "-1".

Для того, чтобы передвигаться по массиву в обратном порядке (с конца в начало), в качестве шага также можно использовать -1: `a[ : :-1]`.


_Проверьте данные утверждения на практике в окне ниже. Переверните произвольный массив задом-наперёд._

In [ ]:
a = np.arange(10)**2
print(a)
a[::-1]

aa = a[:7:2]
print(aa)
print(a[7])

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  4 16 36]
49


__*Для данного массива `a = np.arange(10)**2` Проверьте, включается ли `a[7]` в интервал среза a[:7:2]? Ответ напишите после двух звёздочек, дважды щёлкнув по полю:*__

**Нет, не включается**

_Для того же массива `a` с помощью срезов установите 3, 6 и 9 элементам в качестве значения число -55._

_Модифицируйте полученный массив `a` с помощью операции взятия среза и "переворота" так, чтобы нулевой элемент остался на своём месте, а оставшаяся часть массива развернулась задом-наперёд._

_В итоге массив `a` должен содержать следующую последовательность: 0, -55, 64, 49, -55, 25, 16,  -55,  4,  1._

In [ ]:
a = np.arange(10)**2
b = a[-55:7:3]
print(b)

c = a[-55:7:6]
print(c)

d = a[-55:7:9]
print(d)

e = a[:1:-1]
print(e)

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]


[ 0  9 36]
[ 0 36]
[0]
[81 64 49 36 25 16  9  4]


Доступ к элементам многомерных массивов осуществляется через выбор индекса по каждой оси. Индексация в этом случае производится через запятую внутри двойных квадратных скобок: 
- `a[0, 2]` -- нулевая строка и второй столбец массива `a`, 
- `a[1:3, 2]` -- элементы из 1 и 2 строки второго столбца.
- `a[:, 2]` -- элементы из всех строк 2го стобца.

Если количество индексов меньше числа осей, то недостающие индексы автоматически заполняются двоеточием:
- `a[1]` -- все числа из 1 строки матрицы `a`.

Для "недостающих" индексов также наравне с двоеточием можно использовать троеточие:
```python
a = np.array( [[[ 1, 2, 3], [ 11, 12, 13]], 
                [[101,102,103], [111,112,113]]]) #трёхмерный массив (2 двумерных массива)
а[1,...]   # аналогично a[1,:,:] или a[1]
а[...,2]   # аналогично a[:,:,2]
```

_Создайте двумерный массив (размер >= 4х5) и напечатайте все элементы:_
- _располагающиеся в 2, 3 и 4 столбцах;_
- _располагающиеся в чётных строках;_
- _располагающиеся в 2, 3 и 4 столбцах чётных строк:_

In [ ]:
a = np.arange(20).reshape(4,5)
print(a)
print("\n")

a1 = a[:,1:4]
print(a1)
print("\n")

a2 =a[1:5:2,:]
print(a2)
print("\n")

a3 = a[1:5:2,1:4]
print(a3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


[[ 5  6  7  8  9]
 [15 16 17 18 19]]


[[ 6  7  8]
 [16 17 18]]


Обратите внимание, что **срезы не создают новый массив при работе с numpy-массивами**. Они возвращают специальный объект, который работает с теми же данными, которые находятся в исходном массиве. Например, следующий код изменяет данные массива `a` через массив `b`:
```Python
a = np.array([1, 2, 3, 4])
b = a[::2]
b[1] = 0
a
```
В результате будет выведено:
```Python
array([1, 2, 0, 4])
```
**Такое поведение отличается от поведения обычных list-списков Python - в них срезы создают копию данных**. 

Данная особенность срезов `ndarray` может привести к неожиданным (и неприятным!) последствиям, такие ошибки в коде сложно отловить. Чтобы обезопасить себя, в таких случаях рекомендуется делать независимую копию данных -- для этого можно использовать функцию `np.array` или метод `np.copy()`. Например, в следующем коде объекты с именами `a` и `b` независимы друг от друга:

```Python
a = np.array([1, 2, 3, 4])
b = np.array(a[::2])
b[1] = 0
print(a)
b
```
В результате будет выведено
```Python
array([1, 2, 3, 4])
array([1, 0])
```
_Проверьте примеры из этого раздела в следующей пустой ячейке кода, используя свой массив `a`. Также попробуйте создать копию массива `ndarray` с помощью метода `np.copy()`._

In [ ]:
a = np.array([-2,10,4,6])

b =np.copy(a)
print(b)

a[0] =4
print(a)


[-2 10  4  6]
[ 4 10  4  6]


**Итерация по `ndarray`**

Итерация по массивам производится по первому индексу:

```python
for row in a:
    print(row)
```

_Проверьте данный факт на двумерном массиве._

In [ ]:
a = np.array([[7,10,4,6],[3,4,1,9]])
for row in a:
  print(row)

[ 7 10  4  6]
[3 4 1 9]


В случае, когда требуется пройти по всему массиву и получить каждый отдельный элемент, используйте атрибут `flat`, который является итератором по всем элементам массива:

```python
for elem in a.flat:
    print(elem)
```

_Проверьте работу `flat` на примере._

In [ ]:
a = np.array([[7,10,4,6],[3,4,1,9]])
for elem in a.flat:
  print(elem)

7
10
4
6
3
4
1
9


**Индексация с помощью массивов целых чисел**

NumPy предлагает больше возможностей для работы с индексами, нежели стандартные последовательности или списки Python. Помимо срезов и индексации целыми числами, существует возможность индексации массивами целых чисел и массивами логических переменных.

Рассмотрим пример индексации с помощью массива целых чисел:
```python
a = np.arange(12)**2         #  квадраты чисел от 0 до 11
i = [1, 1, 3, 8, 5]          #  массив индексов, может задаваться как обычным list, так и ndarray

```

_Проверьте содержимое `a[i]`. Попробуйте задавать массив `i` как list и как ndarray._

In [ ]:
a = np.arange(12)**2
i = [1, 1, 3, 8, 5,8]
ii =np.array([1,2,5,3]) 
print(a)
print(a[i])
a[ii]


[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25 64]


array([ 1,  4, 25,  9])

**_Напишите, какое должно быть содержимое массива `i`, чтобы при выводе `a[i]` печатались все чётные числа массива:_**

**Массив a[i] должен содержать чётные элементы чтобы печатались чётные числа массива**

_С помощью фукции `np.arange` создайте такой массив `i`, чтобы с его помощью можно было распечатать только те числа, которые стоят на чётных позициях массива `a`:_

In [ ]:
ot =12
evn =0
a = np.arange(ot)**2
i =np.array([2,4,6,8,10])
a[i]

array([  4,  16,  36,  64, 100])

Такая индексация может быть полезна в случае, когда, например, требуется присвоить одинаковое значение сразу нескольким элементами массива:
```python
a = np.arange(5)
a[[1,3,4]] = 0
```
_Проверьте содержимое массива `a`._ 

In [ ]:
a = np.arange(5)
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

 **Индексация с помощью логических выражений**
 
При индексации с помощью логических выражений можно выбрать из массива только те элементы, для которых выполняется заданное условие. 

К примеру, требуется обнулить все отрицательные элементы массива:
```python
a = np.arange(-10, 10)
a[a<0] = 0
```
_Проверьте работу данного кода._

*С помощью функции `count_nonzero` библиотеки NumPy подсчитайте количество ненулевых значений массива `a`. Справку по данной функции можно получить по ссылке: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.count_nonzero.html*



In [ ]:
a = np.arange(-10, 10)
b = np.count_nonzero(a)

print(b)

19


_Создайте числовой массив `ndarray`. Напишите логическое выражение с данным массивом (как для примера выше `a<0`, например) и присвойте ему какое-либо имя (например, `b = a < 0`). Распечатайте содержимое полученного имени. Проанализируйте, что получилось в результате?_

In [ ]:
a= np.array([[2,4,5,5,99],[2,11,23,454,12]])
b = a >= 5
a[b]

array([  5,   5,  99,  11,  23, 454,  12])

_Создайте 2 массива случайных чисел: первый на 50 элементов, второй -- на 5000. Для каждого из них подсчитайте процентное соотношение элементов массива, больших 0.5 и меньших 0.5._

_Указание: могут пригодиться функции `np.random.random()` и `np.size`._

_В блоке под кодом сделайте вывод:_

In [ ]:
mass_one = np.random.random(50)
mass_two = np.random.random(5000)

mass_one = mass_one > 0.5
mass_one_size = np.size(mass_one)
mass_one_more = mass_one[mass_one]
mass_one_ms= np.size(mass_one_more)
mass_one_result = (mass_one_ms * 100 /mass_one_size)
print("Процент элементов больше 0.5 в первом массиве")
print(mass_one_result)
print("Процент элементов меньше 0.5 в первом массиве")
print(100 - mass_one_result)

print("\n")

mass_two = mass_two > 0.5
mass_two_size = np.size(mass_two)
mass_two_more = mass_two[mass_two]
mass_two_ms= np.size(mass_two_more)
mass_two_result = (mass_two_ms * 100 /mass_two_size)
print("Процент элементов больше 0.5 во втором массиве")
print(mass_two_result)
print("Процент элементов меньше 0.5 во втором массиве")
print(100 - mass_two_result)

Процент элементов больше 0.5 в первом массиве
56.0
Процент элементов меньше 0.5 в первом массиве
44.0


Процент элементов больше 0.5 во втором массиве
49.78
Процент элементов меньше 0.5 во втором массиве
50.22


**Напишите вывод здесь:**

**В массиве на 5000 элементов чаще встречаются значения больше 0.5**

**Разброс ~8%**





Для работы с логическими массивами существуют такие полезные функции, как `logical_and`, `logical_or`, `logical_not` и др. (https://docs.scipy.org/doc/numpy/reference/routines.logic.html)
При необходимости прочитайте их описание и примените при выполнении следующего задания.

_В массиве `payroll` содержатся данные о заработной плате работников фирмы. Заработная плата работников отличается и зависит от категории: директора, менеджеры, рабочие, вспомогательный персонал. Требуется подсчитать:_

   _1) количество сотрудников в каждой категории;_

   _2) суммарный размер ФОТ для категории рабочих;_

   _3) суммарный размер ФОТ для категорий директоров, менеджеров и вспомогательного персонала (совместный)._

_На основе полученных результатов сделайте вывод о величине расходов фирмы на оплату труда рабочих в процентном соотношении от размера ФОТ._

_Категории работников определите, исходя из рамеров з/п: известно, что директора получают > 1000, менеджеры -- от 100 до 1000, рабочие -- от 20 до 100, вспомогательный персонал -- от 5 до 20._

_Выполните задание без использования циклов._

In [ ]:
payroll = np.array([77, 34, 10, 1500, 120, 55, 68, 500, 56, 1100, 80, 90, 30, 15])#данные о заработной плате работников фирмы

director = payroll >1000
director_mass=payroll[director]
director_size = np.size(director_mass)
print("Количество директоров")
print(director_size)
director_sum = np.sum(director_mass)

manager = np.logical_and(payroll >= 100, payroll < 1000)
manager_mass = payroll[manager]
manager_size = np.size(manager_mass)
print("Количество менеджеров")
print(manager_size)
manager_sum = np.sum(manager_mass)

worker = np.logical_and(payroll >= 20, payroll < 100)
worker_mass = payroll[worker]
worker_size = np.size(worker_mass)
print("Количество рабочих")
print(worker_size)
worker_sum = np.sum(worker_mass)
print("Cумма зп рабочих")
print(worker_sum)

sup_worker = np.logical_and(payroll >= 5, payroll < 20)
sup_worker_mass = payroll[sup_worker]
sup_worker_size = np.size(sup_worker_mass)
print("Количество вспомогательных рабочих")
print(sup_worker_size)
sup_worker_sum = np.sum(sup_worker_mass)

sum = director_sum + manager_sum +worker_sum+ sup_worker_sum
print("Сумма расходов на ФОТ")
print(sum)

sum_w = round((worker_sum * 100 / sum))
print("Процент расходов ФОТ на зп рабочих")
print(sum_w)


Количество директоров
2
Количество менеджеров
2
Количество рабочих
8
Cумма зп рабочих
490
Количество вспомогательных рабочих
2
Сумма расходов на ФОТ
3735
Процент расходов ФОТ на зп рабочих
13


**Транспонирование**

Свойство массива `T` возвращает транспонированный массив. 

Например:
```Python
a = np.array([[1, 2], [3, 4]])
a.T
```
выведет
```Python
array([[1, 3],
       [2, 4]])
```
Аналогичный эффект можно достигнуть, применив функцию `np.transpose()`
```Python
np.transpose(a)
```
выведет
```python
array([[1, 3],
       [2, 4]])

```
Обратите внимание, что транспонирование не влияет на одномерные массивы – транспонирование это изменение порядка осей, а у одномерных массивов она одна.

_Создайте и транспонируйте трехмерный массив в следующей ячейке кода._

In [ ]:
a = np.arange(30).reshape(5,3,2)
a.T

array([[[ 0,  6, 12, 18, 24],
        [ 2,  8, 14, 20, 26],
        [ 4, 10, 16, 22, 28]],

       [[ 1,  7, 13, 19, 25],
        [ 3,  9, 15, 21, 27],
        [ 5, 11, 17, 23, 29]]])

**Увеличение числа измерений**

Одним из вариантов увеличения числа измерений является использование срезов и специального значения `np.newaxis`. Этот способ иллюстрируется следующим примером:
```Python
x = np.array([2,5,18,14,4])
y = x[:, np.newaxis]
y
```
Результатом работы будет массив с двумя измерениями:
```Python
[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]
 ```
 
 Другим вариантом является использование функций `np.atleast_2d` и `np.atleast_3d`, которые проверяют, что их аргумент имеет по крайней мере два (три) измерения, и в случае необходимости добавляют недостающие:
```Python
np.atleast_3d(x)
```
Выведет:
```Python
array([[[ 2],
        [ 5],
        [18],
        [14],
        [ 4]]])
```
_Создайте два одномерных вектора, в одном N элементов, в другом - M. Умножьте эти два вектора как вектор-столбец на вектор-строку (так, чтобы в результате получилась матрица размера NxM). Выполните данное задание без использования операции транспонирования._

_**Бонусное 1**: используйте только увеличение размерности, функцию матричного(скалярного) умножения и транспонирование._

_**Бонусное 2**: используйте только reshape и функцию матричного(скалярного) умножения._

In [ ]:
a = np.array([2,4,12,45])
b = np.array([42,1,23,56])
y = a[:, np.newaxis]
y * b 

array([[  84,    2,   46,  112],
       [ 168,    4,   92,  224],
       [ 504,   12,  276,  672],
       [1890,   45, 1035, 2520]])

**Конкатенация массивов**

При обработке данных часто требуется собирать большие массивы из фрагментов меньшего размера. Функцией, выполняющей соединение (конкатенацию) массивов является `np.concatenate`:
```Python
np.concatenate((a1, a2, ...), axis=0)
```

Параметр `axis` определяет ось, по которой будет выполнена конкатенация. По умолчанию `axis=0` что соответствует конкатенации строк:
```Python
a = np.array([[1,2], [3,4]])  #a.shape: (2, 2)
b = np.array([[5, 6]])        #b.shape: (1, 2)
np.concatenate((a, b), axis=0)
```
Выведет:
```Python
array([[1, 2],
       [3, 4],
       [5, 6]])
```
Для того, чтобы конкатенация сработала, все соединяемые матрицы должны иметь совпадающие размеры по совмещаемым осям (для оси, используемой для объединения, это не важно). Поэтому, обратите внимание, в примере вектор `b` является двумерной матрицей(!), так же как и `a`.

Чтобы выполнить *конкатенацию по столбцам* следует задать параметр `axis=1`:
```Python
np.concatenate((a, b.T), axis=1)
```
Получим:
```Python
array([[1, 2, 5],
       [3, 4, 6]])
```

Обратите внимание, что при конкатенации по столбцам в этом примере необходимо транспонировать матрицу `b`, так как иначе матрицы будут не совместимы друг с другом по форме. 

Функция `np.stack` соединяет матрицы вдоль нового измерения. Например, с её помощью можно, склеить двумерную матрицу из одномерных векторов - строк:

```Python
u = np.array([1, 2])
v = np.array([3, 4])
w = np.array([5, 6])
np.stack((u, v, w))
```
Получим:
```Python
array([[1, 2],
       [3, 4],
       [5, 6]])
```

Функции `np.vstack` и `np.hstack` соединяют массивы вертикально и горизонтально соответственно. Эти функции считаются устаревшими, однако последняя из них удобна тем, что позволяют присоединить вектор к матрице не увеличивая предварительно размерность вектора до двух. Это может быть полезно в ситуции, когда строки матрицы вычисляются последовательно и нужно дописывать их к ранее накопленным данным.

```Python
M = np.array([[1, 2], [3, 4]])
w = np.array([5, 6])
np.vstack((M, w))
```
Получим:
```Python
array([[1, 2],
       [3, 4],
       [5, 6]])
```
И наконец, функция `np.dstack` использовалась для соединения двумерных массивов (например, изображений) по третьему измерению. Вместо этой функции теперь также рекомендуется использовать `np.stack`. 

_Запустите код в следующей ячейке._

_Исправьте допущенную ошибку, учитывая, что требовалось получить следующий массив:
[[-1,  2], [30,  0], [ 1, 20], [ 2, -6]])._

In [ ]:
c = np.array([[-1, 2], [30, 0], [1, 20]]) 
b = np.array([[2, -6]])    
np.concatenate((c, b), axis=0)

array([[-1,  2],
       [30,  0],
       [ 1, 20],
       [ 2, -6]])

_Напишите фрагмент программы, который последовательно добавляет к произвольной матрице несколько новых строк и столбцов. Начните с пустой матрицы и печатайте промежуточный вариант после каждого добавления с помощью функции `print`._

In [ ]:
empty_mass =np.zeros(shape=(3,3))
print(empty_mass)
print("\n")

dop_mass = np.array([[1,2,3]])
dop = np.array([[4]])
print(dop_mass)
print("\n")

double_dop_mass = np.concatenate((dop_mass,dop),axis = 1)
print(double_dop_mass)
print("\n")

row_count_mass =np.vstack((empty_mass,dop_mass))
print(row_count_mass)
print("\n")

column_count_mass =np.concatenate((row_count_mass,double_dop_mass.T),axis = 1)
print(column_count_mass)
print("\n")

i = 0
while i < 10:

  cycle_row_count =np.concatenate((column_count_mass,double_dop_mass),axis = 0)
  column_count_mass = cycle_row_count
  print(column_count_mass)
  print("\n")

  dop = np.array([[i]])
  cycle_double_dop_mass = np.concatenate((double_dop_mass,dop),axis = 1)
  dop_mass = cycle_double_dop_mass
  double_dop_mass = dop_mass
  print(double_dop_mass)
  print("\n")

  cycle_column_count =np.concatenate((column_count_mass,double_dop_mass.T),axis = 1)
  column_count_mass = cycle_column_count
  print(column_count_mass)
  print("\n")

  i = i + 1

  
  





[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1 2 3]]


[[1 2 3 4]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 3.]]


[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]
 [1. 2. 3. 4.]]


[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


[[1 2 3 4 0]]


[[0. 0. 0. 1. 1.]
 [0. 0. 0. 2. 2.]
 [0. 0. 0. 3. 3.]
 [1. 2. 3. 4. 4.]
 [1. 2. 3. 4. 0.]]


[[0. 0. 0. 1. 1.]
 [0. 0. 0. 2. 2.]
 [0. 0. 0. 3. 3.]
 [1. 2. 3. 4. 4.]
 [1. 2. 3. 4. 0.]
 [1. 2. 3. 4. 0.]]


[[1 2 3 4 0 1]]


[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 2. 2. 2.]
 [0. 0. 0. 3. 3. 3.]
 [1. 2. 3. 4. 4. 4.]
 [1. 2. 3. 4. 0. 0.]
 [1. 2. 3. 4. 0. 1.]]


[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 2. 2. 2.]
 [0. 0. 0. 3. 3. 3.]
 [1. 2. 3. 4. 4. 4.]
 [1. 2. 3. 4. 0. 0.]
 [1. 2. 3. 4. 0. 1.]
 [1. 2. 3. 4. 0. 1.]]


[[1 2 3 4 0 1 2]]


[[0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 2. 2. 2. 2.]
 [0. 0. 0. 3. 3. 3. 3.]
 [1. 2. 3. 4. 4. 4. 4.]
 [1. 2. 3. 4. 0. 0. 0.]
 [1. 2. 3. 4. 0. 1. 1.]
 [1. 2. 3. 4. 0. 1. 2.]]


[[0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 

**Выполните задания без использования циклов:**

_Найдите евклидово расстояние между 2 векторами, представленными одномерными массивами `ndarray` (векторы задайте самостоятельно)._


In [ ]:
a = np.array([1,6])
b = np.array([42,4])
c = np.linalg.norm(a - b)
print(c)

41.048751503547585


_Найдите сумму элементов главной диагонали двумерного массива (массив задайте самостоятельно)._

_Выполните задание без использования функций получения главной диагонали (diag, diagonal, etc.)._

In [ ]:
a = np.array([[9,6,4],[4,8,1],[2,2,7]])
cd = np.arange(121).reshape(11,11)
print(cd)
cd_triu = np.triu(cd)
cd_tril = np.tril(cd_triu)
otvet = np.sum(cd_tril)
print(otvet)

i = 0
j = 0
otv = 0
cd_size = np.size(cd,axis =1)
while i < cd_size:
  otv = cd[i,i] + otv

  i = i + 1
print(otv)

b = np.arange(cd_size) 
print(b)

c = cd[b,b]
print(c)
otv_c = np.sum(c)
print(otv_c)
  

[[  0   1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43]
 [ 44  45  46  47  48  49  50  51  52  53  54]
 [ 55  56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75  76]
 [ 77  78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97  98]
 [ 99 100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119 120]]
660
660
[ 0  1  2  3  4  5  6  7  8  9 10]
[  0  12  24  36  48  60  72  84  96 108 120]
660


_Найдите среднее гармоническое n положительных чисел (числа задайте самостоятельно)._

In [ ]:
a = np.array([1,2,4,1,41,2,2,4,5])
a_size = np.size(a)
e = a_size / np.sum(1/a)
print(e)


2.1304849884526558


_Найдите взвешенное среднее гармоническое n положительных чисел (числа и веса задайте самостоятельно)._

In [ ]:
a = np.array([1,2,4,1,41,2,2])
b =np.array([0.1,0.2,0.25,0.1,0.1,0.05,0.2])
otvet = np.sum(b)/np.sum(a[::1] / b[::1])
print(otvet)

0.001976284584980237
